### ISSUE TITLE
compiling this on osx fails

### ISSUE THREAD

**Issue by ldanicel** [dapphub/ethsign#6]
osx 10.13.3
$ go build
./ethsign.go:309:36: cannot use gasLimit (type *big.Int) as type uint64 in argument to types.NewContractCreation
./ethsign.go:311:31: cannot use gasLimit (type *big.Int) as type uint64 in argument to types.NewTransaction

**Comment by nanexcool** [comment]
@ldanicel you need to change line https://github.com/dapphub/ethsign/blob/master/ethsign.go#L204 to `MustParseUint64` because of the way Geth changed its gasLimit type.

**Comment by mbrock** [comment]
Sorry for the inconvenience! We mostly build using Nix, so you'll see the default.nix pins the Geth version to v1.7.3 (the latest release). Just `go build` will take the latest Geth commit from master. There are some ways to pin versions with Go tools, but I'm not familiar with them.
